name: Scrape Gaming Sites (Text)

on:
  workflow_dispatch:
  schedule:
    - cron: "23 2 * * *"  # Runs daily at 02:23 UTC

permissions:
  contents: write
  actions: read

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run scraper (rooted)
        env:
          SCRAPER_FIRST_N: ${{ vars.SCRAPER_FIRST_N || '50' }}
          SCRAPER_DYNAMIC: ${{ vars.SCRAPER_DYNAMIC || 'auto' }}
        run: |
          python scrape.py --dynamic "${SCRAPER_DYNAMIC}"

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: text-results
          path: output/*.txt
          if-no-files-found: warn
          retention-days: 14

      - name: Commit & push output to repo
        if: ${{ hashFiles('output/*.txt') != '' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.txt || true
          git commit -m "chore(output): add scrape results [skip ci]" || echo "Nothing to commit"
          git push

      - name: Optional: Notify Make webhook (if set)
        if: ${{ secrets.MAKE_WEBHOOK_URL != '' }}
        env:
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: |
          curl -fsS -X POST \
            -H "Content-Type: application/json" \
            -d "{\"source\":\"github\",\"repo\":\"${{ github.repository }}\",\"run_id\":\"${{ github.run_id }}\",\"sha\":\"${{ github.sha }}\",\"ts\":\"${{ github.run_number }}\"}" \
            "$MAKE_WEBHOOK_URL"
